### PR TITLE
kubernetes: null pointer exception when secret does not exist

### PR DESCRIPTION
**Pull request by bazzuka**
Hello 

When Kubernetes secret not found I got error: 

```
2019-03-20 11:12:11.012 ERROR 8 --- [TaskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
2019-03-20 11:12:10.978 INFO 8 --- [TaskScheduler-1] d.k.v.k.scheduler.ScheduledRefresh : Start refresh of secret...
```

### CODE REVIEW

**Comment by jaywgraves** [comment]
this should fix #11 right?

**Comment by bazzuka** [comment]
Yes, this PR fixes secrets creation for the first time.

**Comment by jaywgraves** [comment]
I pulled and built this PR and tested it against both #11 and #12 test scenarios in my cluster and I still have the same errors.
If I get some more time, I'll try to debug further.

**Comment by DaspawnW** [comment]
Hi @bazzuka,

thank you very much for the merge request, I appended one commit and merged it :-)

**Pull request merged**
